'use client'

import { useState } from 'react'
import { useAuth } from '@/lib/auth-context'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { AlertCircle, Download, RefreshCw, Calendar } from 'lucide-react'

interface WorkoutSession {
  day: string
  exercise: string
  sets: number
  reps: number
  duration?: string
  intensity: string
  notes?: string
}

interface TrainingProgram {
  id: string
  name: string
  duration: string
  goal: string
  generatedAt: string
  sessions: WorkoutSession[]
}

export default function TrainingProgramPage() {
  const { user } = useAuth()
  const [program, setProgram] = useState<TrainingProgram | null>(null)
  const [loading, setLoading] = useState(false)
  const [expanded, setExpanded] = useState<string | null>(null)

  // Mock AI-generated training program
  const mockPrograms: TrainingProgram[] = [
    {
      id: '1',
      name: 'Strength & Endurance Program',
      duration: '12 weeks',
      goal: 'Build muscle and improve cardiovascular fitness',
      generatedAt: new Date().toLocaleDateString(),
      sessions: [
        {
          day: 'Monday',
          exercise: 'Barbell Squats',
          sets: 4,
          reps: 6,
          intensity: 'High',
          notes: 'Rest 2 minutes between sets',
        },
        {
          day: 'Monday',
          exercise: 'Leg Press',
          sets: 3,
          reps: 8,
          intensity: 'High',
          notes: 'Controlled movement',
        },
        {
          day: 'Tuesday',
          exercise: 'Bench Press',
          sets: 4,
          reps: 6,
          intensity: 'High',
          notes: 'Full body engagement',
        },
        {
          day: 'Tuesday',
          exercise: 'Incline Dumbbell Press',
          sets: 3,
          reps: 8,
          intensity: 'Medium',
          notes: '30-degree angle',
        },
        {
          day: 'Wednesday',
          exercise: 'Cardio & Core',
          duration: '45 minutes',
          sets: 1,
          reps: 1,
          intensity: 'Medium',
          notes: '30 min run, 15 min abs circuit',
        },
        {
          day: 'Thursday',
          exercise: 'Deadlifts',
          sets: 4,
          reps: 5,
          intensity: 'High',
          notes: 'Power-focused',
        },
        {
          day: 'Thursday',
          exercise: 'Rows',
          sets: 3,
          reps: 8,
          intensity: 'High',
          notes: 'Explosive pull',
        },
        {
          day: 'Friday',
          exercise: 'Shoulder Press',
          sets: 3,
          reps: 8,
          intensity: 'Medium',
          notes: 'Strict form',
        },
        {
          day: 'Saturday',
          exercise: 'Active Recovery',
          duration: '30 minutes',
          sets: 1,
          reps: 1,
          intensity: 'Low',
          notes: 'Yoga or light stretching',
        },
      ],
    },
  ]

  const generateProgram = async () => {
    setLoading(true)
    // Simulate API call to AI
    await new Promise(resolve => setTimeout(resolve, 1500))
    setProgram(mockPrograms[0])
    setLoading(false)
  }

  const downloadProgram = () => {
    if (!program) return
    const csv = convertToCSV(program)
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${program.name}.csv`
    a.click()
  }

  const convertToCSV = (prog: TrainingProgram) => {
    let csv = `Training Program: ${prog.name}\n`
    csv += `Duration: ${prog.duration}\nGoal: ${prog.goal}\n\n`
    csv += 'Day,Exercise,Sets,Reps,Intensity,Notes\n'
    prog.sessions.forEach(session => {
      csv += `${session.day},${session.exercise},${session.sets},${session.reps},${session.intensity},"${session.notes || ''}"\n`
    })
    return csv
  }

  const groupedSessions = program
    ? program.sessions.reduce(
        (acc, session) => {
          if (!acc[session.day]) acc[session.day] = []
          acc[session.day].push(session)
          return acc
        },
        {} as Record<string, WorkoutSession[]>
      )
    : {}

  return (
    <div className="flex-1 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-foreground mb-2">AI Training Program</h1>
          <p className="text-muted-foreground">
            Personalized workout plans generated by our AI based on your fitness profile
          </p>
        </div>

        {!program ? (
          <Card className="p-8 text-center">
            <AlertCircle className="mx-auto mb-4 text-primary" size={48} />
            <h2 className="text-xl font-semibold mb-2">No Program Generated Yet</h2>
            <p className="text-muted-foreground mb-6">
              Click the button below to generate a personalized training program based on your
              fitness level, objectives, and health profile.
            </p>
            <Button
              onClick={generateProgram}
              disabled={loading}
              size="lg"
              className="bg-primary hover:bg-primary/90"
            >
              {loading ? (
                <>
                  <RefreshCw className="mr-2 animate-spin" size={20} />
                  Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="mr-2" size={20} />
                  Generate Program
                </>
              )}
            </Button>
          </Card>
        ) : (
          <div>
            {/* Program Header */}
            <Card className="p-6 mb-6 bg-gradient-to-r from-primary/10 to-secondary/10">
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-2">{program.name}</h2>
                  <p className="text-muted-foreground flex items-center gap-2">
                    <Calendar size={16} />
                    {program.duration} | Generated: {program.generatedAt}
                  </p>
                </div>
                <div className="flex gap-3">
                  <Button onClick={generateProgram} variant="outline">
                    <RefreshCw className="mr-2" size={18} />
                    Regenerate
                  </Button>
                  <Button onClick={downloadProgram} className="bg-primary hover:bg-primary/90">
                    <Download className="mr-2" size={18} />
                    Download
                  </Button>
                </div>
              </div>
              <p className="text-foreground font-medium mt-4">Goal: {program.goal}</p>
            </Card>

            {/* Weekly Schedule */}
            <div className="grid gap-4">
              {Object.entries(groupedSessions)
                .sort((a, b) => {
                  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
                  return days.indexOf(a[0]) - days.indexOf(b[0])
                })
                .map(([day, sessions]) => (
                  <Card key={day} className="overflow-hidden">
                    <button
                      onClick={() => setExpanded(expanded === day ? null : day)}
                      className="w-full p-4 flex items-center justify-between hover:bg-muted/50 transition"
                    >
                      <h3 className="font-semibold text-foreground text-lg">{day}</h3>
                      <span className="text-sm text-muted-foreground bg-muted px-3 py-1 rounded-full">
                        {sessions.length} exercise{sessions.length !== 1 ? 's' : ''}
                      </span>
                    </button>

                    {expanded === day && (
                      <div className="border-t border-border">
                        {sessions.map((session, idx) => (
                          <div
                            key={idx}
                            className="p-4 border-b border-border last:border-b-0 hover:bg-muted/30 transition"
                          >
                            <div className="flex items-start justify-between mb-3">
                              <div>
                                <h4 className="font-semibold text-foreground">{session.exercise}</h4>
                                <p className="text-sm text-muted-foreground">
                                  {session.sets} sets × {session.reps} reps {session.duration && `(${session.duration})`}
                                </p>
                              </div>
                              <span
                                className={`px-3 py-1 rounded-full text-xs font-medium ${
                                  session.intensity === 'High'
                                    ? 'bg-destructive/20 text-destructive'
                                    : session.intensity === 'Medium'
                                      ? 'bg-primary/20 text-primary'
                                      : 'bg-secondary/20 text-secondary'
                                }`}
                              >
                                {session.intensity} Intensity
                              </span>
                            </div>
                            {session.notes && (
                              <p className="text-sm text-muted-foreground italic">💡 {session.notes}</p>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                  </Card>
                ))}
            </div>

            {/* Regenerate Button */}
            <div className="mt-8 text-center">
              <p className="text-muted-foreground mb-4">
                Not satisfied with this program? Generate a new one with different parameters.
              </p>
              <Button
                onClick={generateProgram}
                disabled={loading}
                size="lg"
                variant="outline"
              >
                {loading ? (
                  <>
                    <RefreshCw className="mr-2 animate-spin" size={20} />
                    Generating...
                  </>
                ) : (
                  <>
                    <RefreshCw className="mr-2" size={20} />
                    Generate New Program
                  </>
                )}
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
